#!/bin/bash

# Set connection name
NIC=**CHANGEME**

# Check if NIC exists
if ! ip link show "$NIC" > /dev/null 2>&1; then
    echo "Network interface $NIC not found!"
    exit 1
fi

# Get public IP
public_ip=$(curl -s http://ipinfo.io/ip 2>/dev/null)

if [ -z "$public_ip" ]; then
    public_ip="Disconnected"
fi

# Get private IPv4 address
private_ipv4=$(ip addr show dev $NIC | grep -w "inet" | awk '{print $2}' | cut -d'/' -f1 | head -n1)
if [ -z "$private_ipv4" ]; then
    private_ipv4="Disconnected"
fi

# Get private IPv6 address
private_ipv6=$(ip addr show dev $NIC | grep -w "inet6" | grep -v "::1" | awk '{print $2}' | cut -d'/' -f1 | head -n1)
if [ -z "$private_ipv6" ]; then
    private_ipv6="Disconnected"
fi

echo "IPv4: ${public_ip} / ${private_ipv4}"
echo "IPv6: ${private_ipv6}"


